const REGISTER = 'REGISTER'
const UPDATE_TEMPERATURE = 'UPDATE_TEMPERATURE'
const START_REQUEST = 'START_REQUEST'
const SUCCESS_REQUEST = 'SUCCESS_REQUEST'
const ERROR_REQUEST = 'ERROR_REQUEST'
const SET_THERMOSTAT_STATE = 'SET_THERMOSTAT_STATE'
const UPDATE_DESIRED_TEMPERATURE = 'UPDATE_DESIRED_TEMPERATURE'

const MS_PER_MINUTE = 60000
const QUERY_GAP = 15 * MS_PER_MINUTE 
const INTERVAL = 5 * MS_PER_MINUTE 
const KEY_LOCAL_STORAGE = 'THERMOSTAT_LOCAL_DUMP'
const THERMOSTAT_STATE = {
  OFF: 'off',
  HEAT: 'heat',
  COOL: 'cool',
  AUTO_HEAT: 'auto_heat',
  AUTO_COOL: 'auto_cool',
  AUTO_STANDBY: 'auto_standby'
}

export {
  REGISTER,
  UPDATE_TEMPERATURE,
  START_REQUEST,
  SUCCESS_REQUEST,
  ERROR_REQUEST,
  INTERVAL,
  QUERY_GAP,
  KEY_LOCAL_STORAGE,
  THERMOSTAT_STATE,
  SET_THERMOSTAT_STATE,
  UPDATE_DESIRED_TEMPERATURE
}
